-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: leads
-- Stores potential client information captured from the portal
CREATE TABLE leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nome VARCHAR(255) REQUIRED,
    email VARCHAR(255),
    telefone VARCHAR(50) REQUIRED, -- WhatsApp number
    origem VARCHAR(50) DEFAULT 'portal_organico', -- Source of the lead
    status VARCHAR(50) DEFAULT 'novo', -- novo, qualificado, em_negociacao, fechado, perdido
    interesse_tipo VARCHAR(50), -- planta, orcamento, duvida
    mensagem TEXT,
    metadata JSONB -- Store extra fields like location, budget range, etc.
);

-- Table: materiais_catalogo
-- Catalog of construction materials with prices and technical details
CREATE TABLE materiais_catalogo (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sistema VARCHAR(100), -- e.g., 'Estrutura LSF', 'Isolamento', 'Acabamento'
    codigo VARCHAR(50) UNIQUE,
    descricao_tecnica TEXT REQUIRED,
    unidade VARCHAR(20), -- m2, un, kg, ml
    preco_unitario DECIMAL(10, 2) REQUIRED,
    fornecedor VARCHAR(100),
    url_origem TEXT, -- URL for scraping updates
    data_ultima_verificacao TIMESTAMP WITH TIME ZONE,
    tags TEXT[]
);

-- Table: plantas
-- Stores 2D plans generated by the system or uploaded
CREATE TABLE plantas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lead_id UUID REFERENCES leads(id),
    prompts_usados TEXT, -- The prompt used to generate this plan
    imagem_url TEXT, -- URL to the generated image (e.g., stored in Supabase Storage or local)
    area_total DECIMAL(10, 2),
    quartos INTEGER,
    wcs INTEGER,
    pisos INTEGER DEFAULT 1,
    tipologia VARCHAR(10), -- T1, T2, T3...
    formato VARCHAR(50), -- L-shaped, U-shaped, Rectangular
    custo_estimado DECIMAL(12, 2),
    status VARCHAR(50) DEFAULT 'rascunho' -- rascunho, aprovada, rejeitada
);

-- Table: orcamentos
-- Detailed budgets generated based on plans and materials
CREATE TABLE orcamentos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lead_id UUID REFERENCES leads(id),
    planta_id UUID REFERENCES plantas(id),
    valor_total DECIMAL(12, 2) REQUIRED,
    margem_aplicada DECIMAL(5, 2) DEFAULT 35.00, -- Percentage
    dados_detalhados JSONB, -- Full breakdown of the budget lines
    url_pdf TEXT, -- Link to generated PDF
    status VARCHAR(50) DEFAULT 'gerado' -- gerado, enviado, visualizado, aprovado
);

-- Table: artigos
-- SEO content for the portal
CREATE TABLE artigos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_at TIMESTAMP WITH TIME ZONE,
    titulo VARCHAR(255) REQUIRED,
    slug VARCHAR(255) UNIQUE REQUIRED,
    conteudo_html TEXT REQUIRED,
    resumo TEXT,
    categoria VARCHAR(50), -- plantas, custos, metodos, noticias
    autor VARCHAR(100) DEFAULT 'Equipa Casas LSF',
    tags TEXT[],
    imagem_destaque_url TEXT,
    status VARCHAR(50) DEFAULT 'rascunho' -- rascunho, publicado, arquivado
);

-- Indexes for performance
CREATE INDEX idx_leads_telefone ON leads(telefone);
CREATE INDEX idx_artigos_slug ON artigos(slug);
CREATE INDEX idx_materiais_sistema ON materiais_catalogo(sistema);
