"""
Public catalogue of plantas generated by leads.

Endpoints:
- GET /api/plantas-publicas              — paginated listing, filterable by tipologia
- GET /api/plantas-publicas/{projeto_id} — full detail (whitelist-safe)
- GET /api/asset/{projeto_id}/{tipo}/{index} — asset proxy (hides telefone from URL)

Design goals:
- Zero PII in public responses or URLs (no telefone, lead_id, names, prompts)
- Cache-Control set aggressively for CDN
- Discovery of 3D/PDF file IDs: MVP reads from `projeto_assets_cache` table
  in casas_lsf DB. Cache miss → returns 404 for that asset (Fase 2 adds
  background job to populate cache from Drive API).
"""
from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Body, HTTPException, Query, Response
from fastapi.responses import JSONResponse
from sqlalchemy import text

from .database import engineering_engine, engine as casas_lsf_engine
from .drive_helper import extract_drive_file_ids, fetch_drive_bytes


router = APIRouter(tags=["plantas-publicas"])


# Campo SQL que exclui projetos sem foto e sem orçamento
QUALIFIED_WHERE = """
    p.ativo = true
    AND p.deleted_at IS NULL
    AND p.tipo_obra = 'moradia'
    AND p.tipologia IS NOT NULL
    AND EXISTS (
        SELECT 1 FROM plantas_geradas pg
         WHERE pg.projeto_id = p.id
           AND pg.google_drive_link IS NOT NULL
    )
    AND EXISTS (
        SELECT 1 FROM orcamentos o
         WHERE o.projeto_id = p.id
    )
"""


@router.get("/api/plantas-publicas")
async def list_plantas(
    tipologia: Optional[str] = None,
    limit: int = Query(24, ge=1, le=100),
    offset: int = Query(0, ge=0),
):
    """Paginated listing of publishable plantas."""
    if not engineering_engine:
        raise HTTPException(503, "Engineering DB unavailable")

    filters = [QUALIFIED_WHERE]
    params: dict = {"limit": limit, "offset": offset}
    if tipologia:
        filters.append("AND UPPER(p.tipologia) = UPPER(:tipologia)")
        params["tipologia"] = tipologia

    sql = f"""
        SELECT
            p.id,
            p.tipologia,
            p.area_m2,
            p.num_pisos,
            p.tem_cave,
            p.tem_sotao,
            p.created_at,
            (SELECT MAX(o.valor_total)
               FROM orcamentos o
              WHERE o.projeto_id = p.id) AS valor_total,
            (SELECT o.padrao_acabamento
               FROM orcamentos o
              WHERE o.projeto_id = p.id
              ORDER BY o.valor_total DESC NULLS LAST
              LIMIT 1) AS padrao_acabamento
        FROM projetos p
        WHERE {' '.join(filters)}
        ORDER BY p.created_at DESC NULLS LAST
        LIMIT :limit OFFSET :offset
    """

    count_sql = f"SELECT COUNT(*) FROM projetos p WHERE {' '.join(filters)}"
    count_params = {k: v for k, v in params.items() if k not in ("limit", "offset")}

    try:
        async with engineering_engine.connect() as conn:
            total = (await conn.execute(text(count_sql), count_params)).scalar() or 0
            rows = (await conn.execute(text(sql), params)).fetchall()
    except Exception as e:
        raise HTTPException(500, f"Query error: {str(e)[:120]}")

    items = []
    for r in rows:
        d = dict(r._mapping)
        projeto_id = d["id"]
        area_m2 = float(d["area_m2"]) if d.get("area_m2") is not None else None
        area_int = int(area_m2) if area_m2 else 0
        slug = f"{area_int}m2-chave-na-mao-{projeto_id}" if area_int else f"modelo-chave-na-mao-{projeto_id}"
        tipo_lower = (d.get("tipologia") or "").lower()
        items.append({
            "id": projeto_id,
            "tipologia": d.get("tipologia"),
            "area_m2": area_m2,
            "num_pisos": d.get("num_pisos"),
            "tem_cave": d.get("tem_cave"),
            "tem_sotao": d.get("tem_sotao"),
            "valor_total": float(d["valor_total"]) if d.get("valor_total") is not None else None,
            "padrao_acabamento": d.get("padrao_acabamento"),
            "slug": slug,
            "url": f"/plantas/tipologia/{tipo_lower}/{slug}",
            "thumbnail_url": f"/api/asset/{projeto_id}/planta2d/0",
            "created_at": d["created_at"].isoformat() if d.get("created_at") else None,
        })

    return JSONResponse(
        content={
            "items": items,
            "total": int(total),
            "limit": limit,
            "offset": offset,
        },
        headers={"Cache-Control": "public, max-age=600, s-maxage=3600"},
    )


@router.get("/api/plantas-publicas/{projeto_id}")
async def get_planta_detail(projeto_id: int):
    """Full detail for one projeto — PII-safe."""
    if not engineering_engine:
        raise HTTPException(503, "Engineering DB unavailable")

    try:
        async with engineering_engine.connect() as conn:
            row = (
                await conn.execute(
                    text(f"""
                        SELECT
                            p.id,
                            p.tipologia,
                            p.area_m2,
                            p.num_pisos,
                            p.tem_cave,
                            p.tem_sotao,
                            p.created_at,
                            (SELECT pg.google_drive_link
                               FROM plantas_geradas pg
                              WHERE pg.projeto_id = p.id
                                AND pg.google_drive_link IS NOT NULL
                              ORDER BY pg.versao DESC, pg.created_at DESC
                              LIMIT 1) AS plantas_drive_link,
                            (SELECT MAX(valor_total) FROM orcamentos o WHERE o.projeto_id = p.id) AS valor_total,
                            (SELECT valor_materiais FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS valor_materiais,
                            (SELECT valor_mao_obra FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS valor_mao_obra,
                            (SELECT valor_indiretos FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS valor_indiretos,
                            (SELECT bdi_percentual FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS bdi_percentual,
                            (SELECT padrao_acabamento FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS padrao_acabamento,
                            (SELECT quantitativos FROM orcamentos o WHERE o.projeto_id = p.id ORDER BY valor_total DESC NULLS LAST LIMIT 1) AS quantitativos
                        FROM projetos p
                        WHERE p.id = :pid AND {QUALIFIED_WHERE.replace("p.", "p.")}
                    """),
                    {"pid": projeto_id},
                )
            ).fetchone()
    except Exception as e:
        raise HTTPException(500, f"Query error: {str(e)[:120]}")

    if not row:
        raise HTTPException(404, "Projeto not found or not publishable")

    d = dict(row._mapping)
    planta_drive_ids = extract_drive_file_ids(d.pop("plantas_drive_link", None))

    # Check cache for 3D + PDF drive IDs
    render_3d_ids: list[str] = []
    pdf_items: list[dict] = []
    try:
        async with casas_lsf_engine.connect() as conn:
            cache = (
                await conn.execute(
                    text("""
                        SELECT render_3d_drive_ids, pdf_drive_ids, pdf_titulos
                          FROM projeto_assets_cache
                         WHERE projeto_id = :pid
                    """),
                    {"pid": projeto_id},
                )
            ).fetchone()
            if cache:
                render_3d_ids = list(cache._mapping.get("render_3d_drive_ids") or [])
                pdf_ids = list(cache._mapping.get("pdf_drive_ids") or [])
                pdf_titulos = list(cache._mapping.get("pdf_titulos") or [])
                for i, fid in enumerate(pdf_ids):
                    titulo = pdf_titulos[i] if i < len(pdf_titulos) else f"Documento {i+1}"
                    pdf_items.append({
                        "titulo": titulo,
                        "url": f"/api/asset/{projeto_id}/pdf/{i}",
                        "index": i,
                    })
    except Exception:
        pass

    # Coerce numeric types
    for num_field in ("area_m2", "valor_total", "valor_materiais", "valor_mao_obra", "valor_indiretos", "bdi_percentual"):
        if d.get(num_field) is not None:
            d[num_field] = float(d[num_field])
    if d.get("created_at"):
        d["created_at"] = d["created_at"].isoformat()

    # Extract IVA + material breakdown from quantitativos.resumo (authoritative source).
    # DB column `valor_materiais` is misleading — it stores total_sem_iva (material + MO),
    # not just material cost. Use resumo.total_material for the real material number.
    quant = d.get("quantitativos") or {}
    resumo = quant.get("resumo") if isinstance(quant, dict) else None
    resumo = resumo if isinstance(resumo, dict) else {}

    def _num(x):
        try:
            return float(x) if x is not None else None
        except (TypeError, ValueError):
            return None

    valor_material = _num(resumo.get("total_material"))
    valor_sem_iva = _num(resumo.get("total_sem_iva"))
    iva_percentual = _num(resumo.get("iva_percentual"))
    iva_valor = _num(resumo.get("iva_valor"))
    preco_m2 = _num(resumo.get("preco_m2"))

    area_int = int(d["area_m2"]) if d.get("area_m2") else 0
    slug = (
        f"{area_int}m2-chave-na-mao-{projeto_id}"
        if area_int
        else f"modelo-chave-na-mao-{projeto_id}"
    )
    tipo_lower = (d.get("tipologia") or "").lower()

    return JSONResponse(
        content={
            "id": d["id"],
            "slug": slug,
            "tipologia": d.get("tipologia"),
            "area_m2": d.get("area_m2"),
            "num_pisos": d.get("num_pisos"),
            "tem_cave": d.get("tem_cave"),
            "tem_sotao": d.get("tem_sotao"),
            "valor_total": d.get("valor_total"),
            "valor_materiais": valor_material if valor_material is not None else d.get("valor_materiais"),
            "valor_mao_obra": d.get("valor_mao_obra"),
            "valor_indiretos": d.get("valor_indiretos"),
            "valor_sem_iva": valor_sem_iva,
            "iva_percentual": iva_percentual,
            "iva_valor": iva_valor,
            "preco_m2": preco_m2,
            "bdi_percentual": d.get("bdi_percentual"),
            "padrao_acabamento": d.get("padrao_acabamento"),
            "quantitativos": d.get("quantitativos"),
            "url": f"/plantas/tipologia/{tipo_lower}/{slug}",
            "planta_2d_count": len(planta_drive_ids),
            "planta_2d_urls": [f"/api/asset/{projeto_id}/planta2d/{i}" for i in range(len(planta_drive_ids))],
            "render_3d_count": len(render_3d_ids),
            "render_3d_urls": [f"/api/asset/{projeto_id}/render3d/{i}" for i in range(len(render_3d_ids))],
            "pdfs": pdf_items,
            "created_at": d.get("created_at"),
        },
        headers={"Cache-Control": "public, max-age=3600, s-maxage=86400"},
    )


@router.get("/api/admin/lead-diagnostico")
async def lead_diagnostico(telefone: str, secret: str):
    """Diagnostic endpoint: given a telefone, report if the projeto qualifies
    for public auto-publishing. Identifies which of the 3 requirements is
    missing (tipologia/ativo, plantas_geradas.google_drive_link, orcamentos).

    Protected by a shared secret query param to avoid PII leak.
    """
    import os

    expected_secret = os.environ.get("ADMIN_DIAG_SECRET", "diagnostico-lsf-2026-abril")
    if secret != expected_secret:
        raise HTTPException(404, "Not found")

    if not engineering_engine:
        raise HTTPException(503, "Engineering DB unavailable")

    # Normalize phone (strip +, spaces)
    tel_clean = "".join(c for c in telefone if c.isdigit())

    try:
        async with engineering_engine.connect() as conn:
            # Find projeto by phone (try both raw telefone and common variations)
            projeto_row = (
                await conn.execute(
                    text("""
                        SELECT id, ativo, deleted_at, tipo_obra, tipologia, area_m2,
                               num_pisos, created_at, updated_at
                          FROM projetos
                         WHERE telefone = :tel
                            OR telefone = CONCAT('+351', :tel)
                            OR telefone = CONCAT('351', :tel)
                         ORDER BY created_at DESC
                         LIMIT 1
                    """),
                    {"tel": tel_clean},
                )
            ).fetchone()

            if not projeto_row:
                return {
                    "found": False,
                    "telefone_consultado": tel_clean,
                    "conclusion": "Nenhum projeto encontrado com este telefone na engineering DB",
                }

            p = dict(projeto_row._mapping)
            projeto_id = p["id"]

            # Check plantas_geradas
            pg_row = (
                await conn.execute(
                    text("""
                        SELECT COUNT(*) AS total,
                               COUNT(google_drive_link) AS com_drive_link,
                               COUNT(google_drive_file_id) AS com_file_id,
                               MAX(created_at) AS ultima_criada
                          FROM plantas_geradas
                         WHERE projeto_id = :pid
                    """),
                    {"pid": projeto_id},
                )
            ).fetchone()
            pg = dict(pg_row._mapping) if pg_row else {}

            # Check orcamentos
            orc_row = (
                await conn.execute(
                    text("""
                        SELECT COUNT(*) AS total,
                               MAX(valor_total) AS maior_valor,
                               MAX(updated_at) AS ultimo_update,
                               (SELECT padrao_acabamento
                                  FROM orcamentos o2
                                 WHERE o2.projeto_id = :pid
                                 ORDER BY valor_total DESC NULLS LAST
                                 LIMIT 1) AS padrao_top
                          FROM orcamentos
                         WHERE projeto_id = :pid
                    """),
                    {"pid": projeto_id},
                )
            ).fetchone()
            orc = dict(orc_row._mapping) if orc_row else {}

    except Exception as e:
        raise HTTPException(500, f"Query error: {str(e)[:120]}")

    # Evaluate qualification
    blockers = []
    if not p.get("ativo"):
        blockers.append("projetos.ativo = false")
    if p.get("deleted_at"):
        blockers.append(f"projetos.deleted_at = {p['deleted_at']}")
    if p.get("tipo_obra") != "moradia":
        blockers.append(f"tipo_obra = '{p.get('tipo_obra')}' (precisa 'moradia')")
    if not p.get("tipologia"):
        blockers.append("tipologia está vazia")
    if (pg.get("com_drive_link") or 0) == 0:
        blockers.append("plantas_geradas não tem nenhum registo com google_drive_link")
    if (orc.get("total") or 0) == 0:
        blockers.append("não existe registo em orcamentos")

    qualified = len(blockers) == 0

    return {
        "found": True,
        "projeto_id": projeto_id,
        "qualified": qualified,
        "blockers": blockers,
        "projeto": {
            "ativo": p.get("ativo"),
            "deleted_at": p["deleted_at"].isoformat() if p.get("deleted_at") else None,
            "tipo_obra": p.get("tipo_obra"),
            "tipologia": p.get("tipologia"),
            "area_m2": float(p["area_m2"]) if p.get("area_m2") is not None else None,
            "created_at": p["created_at"].isoformat() if p.get("created_at") else None,
            "updated_at": p["updated_at"].isoformat() if p.get("updated_at") else None,
        },
        "plantas_geradas": {
            "total_registos": pg.get("total") or 0,
            "com_drive_link": pg.get("com_drive_link") or 0,
            "com_file_id": pg.get("com_file_id") or 0,
            "ultima_criada": pg["ultima_criada"].isoformat() if pg.get("ultima_criada") else None,
        },
        "orcamentos": {
            "total": orc.get("total") or 0,
            "maior_valor": float(orc["maior_valor"]) if orc.get("maior_valor") is not None else None,
            "padrao": orc.get("padrao_top"),
            "ultimo_update": orc["ultimo_update"].isoformat() if orc.get("ultimo_update") else None,
        },
        "url_publico": (
            f"/plantas/tipologia/{(p.get('tipologia') or '').lower()}/"
            f"{int(p['area_m2']) if p.get('area_m2') else 'modelo'}m2-chave-na-mao-{projeto_id}"
            if qualified else None
        ),
    }


@router.post("/api/admin/sync-assets/{projeto_id}")
async def sync_assets(
    projeto_id: int,
    secret: str = Query(...),
    payload: dict = Body(...),
):
    """Upsert assets cache for a projeto.

    Accepts Drive file IDs discovered by n8n (or manual curl) and stores them
    in `projeto_assets_cache`. After upsert, the detail page + asset proxy
    immediately serve the new 3D renders and PDFs.

    Payload shape:
    {
      "render_3d_drive_ids": ["1abc...", "2def...", ...],  // up to 7
      "pdf_drive_ids": ["3ghi...", "4jkl...", ...],        // up to 4
      "pdf_titulos": ["Mapa de Quantidades", "Cronograma Financeiro", ...]
    }
    """
    import os

    expected_secret = os.environ.get("ADMIN_DIAG_SECRET", "diagnostico-lsf-2026-abril")
    if secret != expected_secret:
        raise HTTPException(404, "Not found")

    # Validate projeto exists and is qualifying
    if not engineering_engine:
        raise HTTPException(503, "Engineering DB unavailable")
    async with engineering_engine.connect() as conn:
        exists = (
            await conn.execute(
                text("SELECT 1 FROM projetos WHERE id = :pid AND ativo = true AND deleted_at IS NULL"),
                {"pid": projeto_id},
            )
        ).scalar()
    if not exists:
        raise HTTPException(404, f"Projeto {projeto_id} not found or inactive")

    # Only update fields present in payload. Preserves other assets when
    # called from separate workflows (PDFs workflow vs 3D workflow).
    has_renders = "render_3d_drive_ids" in payload
    has_pdfs = "pdf_drive_ids" in payload

    if not has_renders and not has_pdfs:
        raise HTTPException(422, "payload must include render_3d_drive_ids and/or pdf_drive_ids")

    render_ids = payload.get("render_3d_drive_ids") if has_renders else None
    pdf_ids = payload.get("pdf_drive_ids") if has_pdfs else None
    pdf_titulos = payload.get("pdf_titulos") if has_pdfs else None

    if has_renders:
        if not isinstance(render_ids, list):
            raise HTTPException(422, "render_3d_drive_ids must be an array")
        render_ids = [str(x) for x in render_ids][:10]
    if has_pdfs:
        if not isinstance(pdf_ids, list):
            raise HTTPException(422, "pdf_drive_ids must be an array")
        pdf_ids = [str(x) for x in pdf_ids][:10]
        pdf_titulos = pdf_titulos or [f"Documento {i+1}" for i in range(len(pdf_ids))]
        if not isinstance(pdf_titulos, list) or len(pdf_titulos) != len(pdf_ids):
            raise HTTPException(422, "pdf_titulos length must match pdf_drive_ids length")
        pdf_titulos = [str(x) for x in pdf_titulos][:10]

    # Read current row for merge
    try:
        async with casas_lsf_engine.begin() as conn:
            current = (
                await conn.execute(
                    text("""
                        SELECT render_3d_drive_ids, pdf_drive_ids, pdf_titulos
                          FROM projeto_assets_cache WHERE projeto_id = :pid
                    """),
                    {"pid": projeto_id},
                )
            ).fetchone()

            final_renders = render_ids if has_renders else (
                list(current._mapping.get("render_3d_drive_ids") or []) if current else []
            )
            final_pdfs = pdf_ids if has_pdfs else (
                list(current._mapping.get("pdf_drive_ids") or []) if current else []
            )
            final_titulos = pdf_titulos if has_pdfs else (
                list(current._mapping.get("pdf_titulos") or []) if current else []
            )

            await conn.execute(
                text("""
                    INSERT INTO projeto_assets_cache (projeto_id, render_3d_drive_ids, pdf_drive_ids, pdf_titulos, synced_at)
                    VALUES (:pid, :rids, :pids, :ptitles, NOW())
                    ON CONFLICT (projeto_id) DO UPDATE SET
                        render_3d_drive_ids = EXCLUDED.render_3d_drive_ids,
                        pdf_drive_ids = EXCLUDED.pdf_drive_ids,
                        pdf_titulos = EXCLUDED.pdf_titulos,
                        synced_at = NOW()
                """),
                {
                    "pid": projeto_id,
                    "rids": final_renders,
                    "pids": final_pdfs,
                    "ptitles": final_titulos,
                },
            )
    except Exception as e:
        raise HTTPException(500, f"Upsert error: {str(e)[:120]}")

    return {
        "ok": True,
        "projeto_id": projeto_id,
        "updated_renders": has_renders,
        "updated_pdfs": has_pdfs,
        "render_3d_count": len(final_renders),
        "pdf_count": len(final_pdfs),
    }


@router.post("/api/admin/generate-3d/{projeto_id}")
async def trigger_3d_generation(projeto_id: int, secret: str = Query(...)):
    """Trigger 3D generation for a projeto via the n8n wrapper workflow.

    Useful for SEO: projetos that were published (have planta 2D + orçamento)
    but lack 3D renders (because the lead never asked) — we generate them
    proactively to enrich the detail page.

    Flow:
      1. Fetch projeto's telefone + lead_id from engineering DB
      2. POST to n8n webhook https://n8n.lsfbuilderpro.com/webhook/generate-3d-casaslsf
      3. n8n wrapper calls Gerar 3D sub-workflow → generates 6 renders
      4. Gerar 3D's own sync node calls back /api/admin/sync-assets → cache populated
      5. Detail page now shows 3D
    """
    import os
    import httpx

    expected_secret = os.environ.get("ADMIN_DIAG_SECRET", "diagnostico-lsf-2026-abril")
    if secret != expected_secret:
        raise HTTPException(404, "Not found")

    if not engineering_engine:
        raise HTTPException(503, "Engineering DB unavailable")

    # Fetch projeto context
    async with engineering_engine.connect() as conn:
        row = (
            await conn.execute(
                text("""
                    SELECT p.id AS projeto_id, p.telefone,
                           (SELECT lead_id FROM plantas_geradas pg
                             WHERE pg.projeto_id = p.id
                               AND pg.lead_id IS NOT NULL
                             ORDER BY created_at DESC LIMIT 1) AS lead_id
                      FROM projetos p
                     WHERE p.id = :pid AND p.ativo = true AND p.deleted_at IS NULL
                """),
                {"pid": projeto_id},
            )
        ).fetchone()

    if not row:
        raise HTTPException(404, f"Projeto {projeto_id} not found or inactive")

    ctx = dict(row._mapping)

    # Check if already has 3D (avoid duplicate/costly regeneration)
    async with casas_lsf_engine.connect() as conn:
        cache = (
            await conn.execute(
                text("""
                    SELECT array_length(render_3d_drive_ids, 1) AS n_renders
                      FROM projeto_assets_cache WHERE projeto_id = :pid
                """),
                {"pid": projeto_id},
            )
        ).fetchone()
    if cache and (cache._mapping.get("n_renders") or 0) > 0:
        return {
            "skipped": True,
            "reason": f"Projeto {projeto_id} already has {cache._mapping['n_renders']} renders in cache",
        }

    # Fire the webhook (non-blocking — Gerar 3D takes ~60-120s, we return immediately)
    webhook_url = os.environ.get(
        "N8N_WEBHOOK_GENERATE_3D",
        "https://n8n.lsfbuilderpro.com/webhook/generate-3d-casaslsf",
    )
    webhook_secret = os.environ.get("N8N_WEBHOOK_SECRET", "diagnostico-lsf-2026-abril")

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                webhook_url,
                headers={"X-Casaslsf-Secret": webhook_secret, "Content-Type": "application/json"},
                json={
                    "projeto_id": ctx["projeto_id"],
                    "telefone": ctx.get("telefone"),
                    "lead_id": ctx.get("lead_id"),
                },
            )
            triggered_at = resp.json() if resp.headers.get("content-type", "").startswith("application/json") else {}
    except httpx.HTTPError as e:
        raise HTTPException(502, f"n8n webhook unreachable: {str(e)[:120]}")

    return {
        "triggered": True,
        "projeto_id": projeto_id,
        "n8n_status": resp.status_code,
        "n8n_response": triggered_at,
        "expected_completion_seconds": 120,
        "check_status_via": f"GET /api/plantas-publicas/{projeto_id} after 2min (render_3d_count)",
    }


@router.get("/api/asset/{projeto_id}/{tipo}/{index}")
async def asset_proxy(projeto_id: int, tipo: str, index: int):
    """Proxy a Drive asset without exposing the filename (which may contain PII)."""
    if tipo not in ("planta2d", "render3d", "pdf"):
        raise HTTPException(404, "Unknown asset type")
    if index < 0 or index > 10:
        raise HTTPException(404, "Asset index out of range")

    file_id: Optional[str] = None

    try:
        if tipo == "planta2d":
            if not engineering_engine:
                raise HTTPException(503, "DB unavailable")
            async with engineering_engine.connect() as conn:
                link = (
                    await conn.execute(
                        text("""
                            SELECT google_drive_link
                              FROM plantas_geradas
                             WHERE projeto_id = :pid
                               AND google_drive_link IS NOT NULL
                             ORDER BY versao DESC, created_at DESC
                             LIMIT 1
                        """),
                        {"pid": projeto_id},
                    )
                ).scalar()
            ids = extract_drive_file_ids(link)
            if index < len(ids):
                file_id = ids[index]
        else:
            # render3d or pdf — from cache table
            async with casas_lsf_engine.connect() as conn:
                cache = (
                    await conn.execute(
                        text("""
                            SELECT render_3d_drive_ids, pdf_drive_ids
                              FROM projeto_assets_cache
                             WHERE projeto_id = :pid
                        """),
                        {"pid": projeto_id},
                    )
                ).fetchone()
            if cache:
                field = "render_3d_drive_ids" if tipo == "render3d" else "pdf_drive_ids"
                ids = list(cache._mapping.get(field) or [])
                if index < len(ids):
                    file_id = ids[index]
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(500, f"Lookup error: {str(e)[:80]}")

    if not file_id:
        raise HTTPException(404, "Asset not found in cache")

    try:
        is_pdf = tipo == "pdf"
        content, content_type = await fetch_drive_bytes(file_id, is_pdf=is_pdf)
    except httpx_error() as e:
        raise HTTPException(502, f"Drive fetch failed: {str(e)[:80]}")

    # Aggressive caching — file IDs never change for a given projeto+tipo+index
    headers = {
        "Cache-Control": "public, max-age=31536000, immutable",
        "Content-Type": content_type,
    }
    if is_pdf:
        headers["Content-Disposition"] = f'inline; filename="modelo-{projeto_id}-doc-{index+1}.pdf"'

    return Response(content=content, headers=headers)


def httpx_error():
    """Lazy import of httpx error class (avoids circular on module load)."""
    import httpx
    return httpx.HTTPError
