// AUTO-GENERATED by scripts/generate-app-routes.mjs
// Do not edit by hand. Regenerate with: npm run gen:routes
// Source: scan of frontend/src/app/<dir>/page.tsx

export const APP_ROUTES: ReadonlySet<string> = new Set([
  "/",
  "/analise-planta",
  "/blog",
  "/casa-lsf-financiamento",
  "/como-funciona",
  "/custos",
  "/empresa-construcao-lsf-portugal",
  "/iva-6-construcao",
  "/metodologia-construtiva",
  "/metodos",
  "/pladur-preco",
  "/plantas",
  "/preco-construcao-lsf-por-m2",
  "/primeira-mundial",
  "/privacidade",
  "/processo-construcao-lsf",
  "/quanto-custa-casa-lsf",
  "/simulador",
  "/sobre-obrasnet",
  "/termos",
]);
